// Token Macro Defintions

#ifndef TOKEN
#define TOKEN(X)
#endif

#ifndef TOKEN_PUNCTUATOR
#define TOKEN_PUNCTUATOR(NAME, SEQ) TOKEN(NAME)
#endif

#undef EOF
TOKEN(EOF)
TOKEN(IDENTIFIER)
TOKEN(NUMERIC_LITERAL)
TOKEN(STRING_LITERAL)
TOKEN(UNKNOWN)

TOKEN_PUNCTUATOR(O_PAREN, '(')
TOKEN_PUNCTUATOR(C_PAREN, ')')
TOKEN_PUNCTUATOR(O_BRACE, '{')
TOKEN_PUNCTUATOR(C_BRACE, '}')
TOKEN_PUNCTUATOR(ADD, '+')
TOKEN_PUNCTUATOR(SUB, '-')
TOKEN_PUNCTUATOR(MULT, '*')
TOKEN_PUNCTUATOR(DIV, '/')
TOKEN_PUNCTUATOR(MODULO, '%')

#undef TOKEN
#undef TOKEN_PUNCTUATOR
